# Generated by Django 5.1.3 on 2024-11-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctores',
            fields=[
                ('idDoctor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('correoElectronico', models.CharField(max_length=100)),
                ('fechaRegistro', models.DateField()),
            ],
        ),
    ]
